import { MockExam } from '@/types/exam';

export const MOCK_EXAMS: MockExam[] = [
  {
    id: 'benchama-math-01',
    name: 'จำลองสอบเข้า ม.1 รร.เบ็ญจะมะมหาราช (ห้อง SMA/Gifted) — คณิตศาสตร์ ชุดที่ 1',
    targetSchool: 'เบ็ญจะมะมหาราช',
    targetSchoolEn: 'benchama',
    subjectId: 'math',
    subjectName: 'คณิตศาสตร์',
    totalQuestions: 25,
    timeLimitMinutes: 60,
    passingScorePercent: 70,
    description: 'เน้นข้อสอบวิเคราะห์เชิงลึก พีชคณิต เรขาคณิตตัดแปะ และโจทย์ปัญหากำไร-ขาดทุน อัตราเร็ว สไตล์ มศว.',
    questionIds: [],
    badgeColor: '#3B82F6',
  },
  {
    id: 'benchama-sci-01',
    name: 'จำลองสอบเข้า ม.1 รร.เบ็ญจะมะมหาราช (ห้อง SMA/Gifted) — วิทยาศาสตร์ ชุดที่ 1',
    targetSchool: 'เบ็ญจะมะมหาราช',
    targetSchoolEn: 'benchama',
    subjectId: 'science',
    subjectName: 'วิทยาศาสตร์',
    totalQuestions: 25,
    timeLimitMinutes: 50,
    passingScorePercent: 70,
    description: 'ข้อสอบกระบวนการทางวิทยาศาสตร์ วิเคราะห์ตารางทดลอง วงจรไฟฟ้า และการแยกสาร',
    questionIds: [],
    badgeColor: '#10B981',
  },
  {
    id: 'chulabhorn-combined-01',
    name: 'จำลองสอบเข้า ม.1 จุฬาภรณราชวิทยาลัย มุกดาหาร — คณิต & วิทย์ (รอบคัดเลือก) ชุดที่ 1',
    targetSchool: 'จุฬาภรณราชวิทยาลัย',
    targetSchoolEn: 'chulabhorn',
    subjectId: 'math',
    subjectName: 'คณิตศาสตร์ & วิทยาศาสตร์',
    totalQuestions: 30,
    timeLimitMinutes: 75,
    passingScorePercent: 75,
    description: 'ข้อสอบคัดเลือกเข้มข้นสไตล์ สสวท. และ มศว. มีทั้งปรนัยและอัตนัยเติมคำตอบ/แสดงวิธีทำ',
    questionIds: [],
    badgeColor: '#8B5CF6',
  },
  {
    id: 'chulabhorn-math-intensive',
    name: 'จำลองสอบเข้า ม.1 จุฬาภรณราชวิทยาลัย มุกดาหาร — คณิตศาสตร์ขั้นสูง (รอบสอง/ข้อเขียน)',
    targetSchool: 'จุฬาภรณราชวิทยาลัย',
    targetSchoolEn: 'chulabhorn',
    subjectId: 'math',
    subjectName: 'คณิตศาสตร์ขั้นสูง',
    totalQuestions: 20,
    timeLimitMinutes: 60,
    passingScorePercent: 80,
    description: 'เน้นโจทย์อัตนัยคิดวิเคราะห์ ลำดับอนุกรม เรขาคณิตเชิงซ้อน และการพิสูจน์แนวคิด',
    questionIds: [],
    badgeColor: '#EC4899',
  },
  {
    id: 'satriwit-pretest-sci-05',
    name: 'ข้อสอบ Pretest วิทยาศาสตร์ ห้องเรียนพิเศษ (Gifted) รร.สตรีวิทยา ครั้งที่ 5',
    targetSchool: 'สตรีวิทยา',
    targetSchoolEn: 'satriwit',
    subjectId: 'science',
    subjectName: 'วิทยาศาสตร์',
    totalQuestions: 30,
    timeLimitMinutes: 60,
    passingScorePercent: 75,
    description: 'ข้อสอบ Pretest วิทยาศาสตร์ห้องเรียนพิเศษ รร.สตรีวิทยา ครอบคลุมฟิสิกส์ เคมี ชีววิทยา โลกและดาราศาสตร์ พร้อมเฉลยละเอียดและภาพประกอบ',
    questionIds: [
      'sw-sci-026', 'sw-sci-027', 'sw-sci-028', 'sw-sci-029', 'sw-sci-030',
      'sw-sci-031', 'sw-sci-032', 'sw-sci-033', 'sw-sci-034', 'sw-sci-035',
      'sw-sci-036', 'sw-sci-037', 'sw-sci-038', 'sw-sci-039', 'sw-sci-040',
      'sw-sci-041', 'sw-sci-042', 'sw-sci-043', 'sw-sci-044', 'sw-sci-045',
      'sw-sci-046', 'sw-sci-047', 'sw-sci-048', 'sw-sci-049', 'sw-sci-050',
      'sw-sci-051', 'sw-sci-052', 'sw-sci-053', 'sw-sci-054', 'sw-sci-055'
    ],
    badgeColor: '#F43F5E',
  },
  {
    id: 'suankularb-pretest-sci-64',
    name: 'ข้อสอบ Pretest วิทยาศาสตร์ รร.สวนกุหลาบวิทยาลัย (ครั้งที่ 8 / ปี 2564)',
    targetSchool: 'สวนกุหลาบวิทยาลัย',
    targetSchoolEn: 'suankularb',
    subjectId: 'science',
    subjectName: 'วิทยาศาสตร์',
    totalQuestions: 30,
    timeLimitMinutes: 60,
    passingScorePercent: 75,
    description: 'ข้อสอบ Pretest วิทยาศาสตร์ รร.สวนกุหลาบวิทยาลัย ครอบคลุมชีววิทยา เคมี ฟิสิกส์ ดาราศาสตร์ พร้อมเฉลยละเอียดและวิเคราะห์แนวคิด',
    questionIds: [
      'sk-sci-64-031', 'sk-sci-64-032', 'sk-sci-64-033', 'sk-sci-64-034', 'sk-sci-64-035',
      'sk-sci-64-036', 'sk-sci-64-037', 'sk-sci-64-038', 'sk-sci-64-039', 'sk-sci-64-040',
      'sk-sci-64-041', 'sk-sci-64-042', 'sk-sci-64-043', 'sk-sci-64-044', 'sk-sci-64-045',
      'sk-sci-64-046', 'sk-sci-64-047', 'sk-sci-64-048', 'sk-sci-64-049', 'sk-sci-64-050',
      'sk-sci-64-051', 'sk-sci-64-052', 'sk-sci-64-053', 'sk-sci-64-054', 'sk-sci-64-055',
      'sk-sci-64-056', 'sk-sci-64-057', 'sk-sci-64-058', 'sk-sci-64-059', 'sk-sci-64-060'
    ],
    badgeColor: '#E11D48',
  },
  {
    id: 'suksanari-pretest-sci-63',
    name: 'ข้อสอบ Pretest วิทยาศาสตร์ รร.ศึกษานารี ปี 2563 (ชุดที่ 2)',
    targetSchool: 'ศึกษานารี',
    targetSchoolEn: 'suksanari',
    subjectId: 'science',
    subjectName: 'วิทยาศาสตร์',
    totalQuestions: 40,
    timeLimitMinutes: 60,
    passingScorePercent: 75,
    description: 'ข้อสอบ Pretest วิทยาศาสตร์ รร.ศึกษานารี เน้นทักษะกระบวนการทดลอง ปัจจัยการเจริญเติบโต กรด-เบส และแรง พร้อมเฉลยละเอียด',
    questionIds: [
      'sn-sci-63-001', 'sn-sci-63-002', 'sn-sci-63-003', 'sn-sci-63-004', 'sn-sci-63-005',
      'sn-sci-63-006', 'sn-sci-63-007', 'sn-sci-63-008', 'sn-sci-63-009', 'sn-sci-63-010',
      'sn-sci-63-011', 'sn-sci-63-012'
    ],
    badgeColor: '#0284C7',
  },
  {
    id: 'rittiya-pre-sci-64',
    name: 'ข้อสอบ Pre-Entrance วิทยาศาสตร์ รร.ฤทธิยะวรรณาลัย ปี 2564',
    targetSchool: 'ฤทธิยะวรรณาลัย',
    targetSchoolEn: 'rittiya',
    subjectId: 'science',
    subjectName: 'วิทยาศาสตร์',
    totalQuestions: 20,
    timeLimitMinutes: 45,
    passingScorePercent: 70,
    description: 'ข้อสอบ Pre-Entrance วิทยาศาสตร์ รร.ฤทธิยะวรรณาลัย ครอบคลุมเรื่องระบบสรีระ สิ่งแวดล้อม วงจรไฟฟ้า และสารละลาย พร้อมเฉลยละเอียด',
    questionIds: [
      'rit-sci-64-061', 'rit-sci-64-062', 'rit-sci-64-063', 'rit-sci-64-064', 'rit-sci-64-065',
      'rit-sci-64-070', 'rit-sci-64-071', 'rit-sci-64-072', 'rit-sci-64-079', 'rit-sci-64-080'
    ],
    badgeColor: '#059669',
  },
  {
    id: 'sarawittaya-pretest-sci-63',
    name: 'ข้อสอบ Pre-test วิทยาศาสตร์ รร.สารวิทยา ปี 2563 (ฉบับที่ 2)',
    targetSchool: 'สารวิทยา',
    targetSchoolEn: 'sarawittaya',
    subjectId: 'science',
    subjectName: 'วิทยาศาสตร์',
    totalQuestions: 40,
    timeLimitMinutes: 60,
    passingScorePercent: 70,
    description: 'ข้อสอบ Pre-test วิทยาศาสตร์ รร.สารวิทยา ครอบคลุมชีววิทยา การสังเคราะห์ด้วยแสง สัตว์เลือดอุ่น-เย็น สารอาหาร และปฏิกิริยาเคมี',
    questionIds: [
      'sara-sci-63-001', 'sara-sci-63-002', 'sara-sci-63-003', 'sara-sci-63-004',
      'sara-sci-63-008', 'sara-sci-63-014', 'sara-sci-63-015'
    ],
    badgeColor: '#D97706',
  },
];
