import { MockExam } from '@/types/exam';

export const MOCK_EXAMS: MockExam[] = [
  {
    id: 'benchama-math-01',
    name: 'จำลองสอบเข้า ม.1 รร.เบ็ญจะมะมหาราช (ห้อง SMA/Gifted) — คณิตศาสตร์ ชุดที่ 1',
    targetSchool: 'เบ็ญจะมะมหาราช',
    targetSchoolEn: 'benchama',
    subjectId: 'math',
    subjectName: 'คณิตศาสตร์',
    totalQuestions: 25,
    timeLimitMinutes: 60,
    passingScorePercent: 70,
    description: 'เน้นข้อสอบวิเคราะห์เชิงลึก พีชคณิต เรขาคณิตตัดแปะ และโจทย์ปัญหากำไร-ขาดทุน อัตราเร็ว สไตล์ มศว.',
    questionIds: [],
    badgeColor: '#3B82F6',
  },
  {
    id: 'benchama-sci-01',
    name: 'จำลองสอบเข้า ม.1 รร.เบ็ญจะมะมหาราช (ห้อง SMA/Gifted) — วิทยาศาสตร์ ชุดที่ 1',
    targetSchool: 'เบ็ญจะมะมหาราช',
    targetSchoolEn: 'benchama',
    subjectId: 'science',
    subjectName: 'วิทยาศาสตร์',
    totalQuestions: 25,
    timeLimitMinutes: 50,
    passingScorePercent: 70,
    description: 'ข้อสอบกระบวนการทางวิทยาศาสตร์ วิเคราะห์ตารางทดลอง วงจรไฟฟ้า และการแยกสาร',
    questionIds: [],
    badgeColor: '#10B981',
  },
  {
    id: 'chulabhorn-combined-01',
    name: 'จำลองสอบเข้า ม.1 จุฬาภรณราชวิทยาลัย มุกดาหาร — คณิต & วิทย์ (รอบคัดเลือก) ชุดที่ 1',
    targetSchool: 'จุฬาภรณราชวิทยาลัย',
    targetSchoolEn: 'chulabhorn',
    subjectId: 'math',
    subjectName: 'คณิตศาสตร์ & วิทยาศาสตร์',
    totalQuestions: 30,
    timeLimitMinutes: 75,
    passingScorePercent: 75,
    description: 'ข้อสอบคัดเลือกเข้มข้นสไตล์ สสวท. และ มศว. มีทั้งปรนัยและอัตนัยเติมคำตอบ/แสดงวิธีทำ',
    questionIds: [],
    badgeColor: '#8B5CF6',
  },
  {
    id: 'chulabhorn-math-intensive',
    name: 'จำลองสอบเข้า ม.1 จุฬาภรณราชวิทยาลัย มุกดาหาร — คณิตศาสตร์ขั้นสูง (รอบสอง/ข้อเขียน)',
    targetSchool: 'จุฬาภรณราชวิทยาลัย',
    targetSchoolEn: 'chulabhorn',
    subjectId: 'math',
    subjectName: 'คณิตศาสตร์ขั้นสูง',
    totalQuestions: 20,
    timeLimitMinutes: 60,
    passingScorePercent: 80,
    description: 'เน้นโจทย์อัตนัยคิดวิเคราะห์ ลำดับอนุกรม เรขาคณิตเชิงซ้อน และการพิสูจน์แนวคิด',
    questionIds: [],
    badgeColor: '#EC4899',
  },
  {
    id: 'satriwit-pretest-sci-05',
    name: 'ข้อสอบ Pretest วิทยาศาสตร์ ห้องเรียนพิเศษ (Gifted) รร.สตรีวิทยา ครั้งที่ 5',
    targetSchool: 'สตรีวิทยา',
    targetSchoolEn: 'satriwit',
    subjectId: 'science',
    subjectName: 'วิทยาศาสตร์',
    totalQuestions: 30,
    timeLimitMinutes: 60,
    passingScorePercent: 75,
    description: 'ข้อสอบ Pretest วิทยาศาสตร์ห้องเรียนพิเศษ รร.สตรีวิทยา ครอบคลุมฟิสิกส์ เคมี ชีววิทยา โลกและดาราศาสตร์ พร้อมเฉลยละเอียดและภาพประกอบ',
    questionIds: [
      'sw-sci-026', 'sw-sci-027', 'sw-sci-028', 'sw-sci-029', 'sw-sci-030',
      'sw-sci-031', 'sw-sci-032', 'sw-sci-033', 'sw-sci-034', 'sw-sci-035',
      'sw-sci-036', 'sw-sci-037', 'sw-sci-038', 'sw-sci-039', 'sw-sci-040',
      'sw-sci-041', 'sw-sci-042', 'sw-sci-043', 'sw-sci-044', 'sw-sci-045',
      'sw-sci-046', 'sw-sci-047', 'sw-sci-048', 'sw-sci-049', 'sw-sci-050',
      'sw-sci-051', 'sw-sci-052', 'sw-sci-053', 'sw-sci-054', 'sw-sci-055'
    ],
    badgeColor: '#F43F5E',
  },
];
