import { Subject } from '@/types/question';

export const SUBJECTS: Subject[] = [
  {
    id: 'math',
    name: 'คณิตศาสตร์',
    nameEn: 'Mathematics',
    slug: 'math',
    icon: 'Calculator',
    color: '#3B82F6', // Blue
    bgColor: '#EFF6FF',
    borderColor: '#BFDBFE',
    description: 'เน้นวิเคราะห์โจทย์ปัญหา เรขาคณิต พีชคณิต แบบรูปความสัมพันธ์ และสถิติแนว มศว./สสวท.',
    totalQuestions: 110,
    order: 1,
    topics: [
      {
        id: 'math-arithmetic',
        subjectId: 'math',
        name: 'จำนวนและการคำนวณ (ห.ร.ม. / ค.ร.น. / เศษส่วน)',
        slug: 'arithmetic',
        description: 'การหารร่วมมาก คูณร่วมน้อย สมบัติจำนวนนับ เศษส่วน ทศนิยม และการหารลงตัว',
        icon: 'Hash',
        totalQuestions: 25,
        order: 1,
      },
      {
        id: 'math-algebra',
        subjectId: 'math',
        name: 'พีชคณิตและสมการเชิงซ้อน',
        slug: 'algebra',
        description: 'การแก้สมการ 1 ตัวแปรและ 2 ตัวแปร แบบรูปและลำดับตัวเลข',
        icon: 'Variable',
        totalQuestions: 22,
        order: 2,
      },
      {
        id: 'math-geometry',
        subjectId: 'math',
        name: 'เรขาคณิตและมิติสัมพันธ์',
        slug: 'geometry',
        description: 'พื้นที่รูปหลายเหลี่ยม ปริมาตร พื้นที่ผิว มุมและเส้นขนาน การตัดแปะชิ้นส่วนรูปทรง',
        icon: 'Shapes',
        totalQuestions: 30,
        order: 3,
      },
      {
        id: 'math-word-problems',
        subjectId: 'math',
        name: 'โจทย์ปัญหาและการประยุกต์',
        slug: 'word-problems',
        description: 'ร้อยละ กำไร-ขาดทุน อัตราเร็ว-ระยะทาง-เวลา การทำงานร่วมกัน',
        icon: 'FileQuestion',
        totalQuestions: 20,
        order: 4,
      },
      {
        id: 'math-statistics',
        subjectId: 'math',
        name: 'สถิติและความน่าจะเป็น',
        slug: 'statistics',
        description: 'การอ่านแผนภูมิแท่ง/วงกลม ค่าเฉลี่ย มัธยฐาน ฐานนิยม และความน่าจะเป็นเบื้องต้น',
        icon: 'BarChart2',
        totalQuestions: 15,
        order: 5,
      },
    ],
  },
  {
    id: 'science',
    name: 'วิทยาศาสตร์',
    nameEn: 'Science',
    slug: 'science',
    icon: 'Atom',
    color: '#10B981', // Emerald
    bgColor: '#ECFDF5',
    borderColor: '#A7F3D0',
    description: 'เน้นกระบวนการทดลอง วิเคราะห์ตารางข้อมูล ฟิสิกส์ เคมี ชีววิทยา และดาราศาสตร์',
    totalQuestions: 150,
    order: 2,
    topics: [
      {
        id: 'sci-biology',
        subjectId: 'science',
        name: 'สิ่งมีชีวิตและกระบวนการดำรงชีวิต',
        slug: 'biology',
        description: 'เซลล์พืช/สัตว์ ระบบร่างกายมนุษย์ การสังเคราะห์ด้วยแสง และการสืบพันธุ์',
        icon: 'HeartPulse',
        totalQuestions: 40,
        order: 1,
      },
      {
        id: 'sci-physics',
        subjectId: 'science',
        name: 'แรง พลังงาน และไฟฟ้าคำนวณ',
        slug: 'physics',
        description: 'วงจรไฟฟ้า แรงลอยตัว แสงและการสะท้อน คานและรอก งานและพลังงาน',
        icon: 'Zap',
        totalQuestions: 40,
        order: 2,
      },
      {
        id: 'sci-chemistry',
        subjectId: 'science',
        name: 'สารและการเปลี่ยนแปลง',
        slug: 'chemistry',
        description: 'การแยกสาร (ตกผลึก, สกัด, กลั่น, โครมาโทกราฟี) สารละลาย กรด-เบส',
        icon: 'FlaskConical',
        totalQuestions: 35,
        order: 3,
      },
      {
        id: 'sci-earth-space',
        subjectId: 'science',
        name: 'โลก ดาราศาสตร์ และอวกาศ',
        slug: 'earth-space',
        description: 'บรรยากาศ ดิน หิน แร่ ปรากฏการณ์น้ำขึ้นน้ำลง ข้างขึ้นข้างแรม และระบบสุริยะ',
        icon: 'Globe',
        totalQuestions: 35,
        order: 4,
      },
    ],
  },
  {
    id: 'english',
    name: 'ภาษาอังกฤษ',
    nameEn: 'English',
    slug: 'english',
    icon: 'Languages',
    color: '#8B5CF6', // Violet
    bgColor: '#F5F3FF',
    borderColor: '#DDD6FE',
    description: 'Grammar in Use, Reading Comprehension, Situational Conversations, and Vocabulary in Context',
    totalQuestions: 100,
    order: 3,
    topics: [
      {
        id: 'eng-grammar',
        subjectId: 'english',
        name: 'Grammar & Structure',
        slug: 'grammar',
        description: 'Tenses, Subject-Verb Agreement, Passive Voice, Prepositions, Conjunctions',
        icon: 'BookCheck',
        totalQuestions: 40,
        order: 1,
      },
      {
        id: 'eng-reading',
        subjectId: 'english',
        name: 'Reading Comprehension',
        slug: 'reading',
        description: 'Short passages, News articles, Scientific extracts, Main idea & Inference',
        icon: 'BookOpen',
        totalQuestions: 30,
        order: 2,
      },
      {
        id: 'eng-conversation',
        subjectId: 'english',
        name: 'Conversations & Vocabulary',
        slug: 'conversation',
        description: 'Everyday dialogues, Contextual clues, Synonyms & Antonyms',
        icon: 'MessageSquare',
        totalQuestions: 30,
        order: 3,
      },
    ],
  },
  {
    id: 'thai',
    name: 'ภาษาไทย',
    nameEn: 'Thai Language',
    slug: 'thai',
    icon: 'BookMarked',
    color: '#F59E0B', // Amber
    bgColor: '#FFFBEB',
    borderColor: '#FDE68A',
    description: 'การอ่านจับใจความ ตีความสาร หลักภาษา สมาส-สนธิ คำราชาศัพท์ และสำนวนไทย',
    totalQuestions: 100,
    order: 4,
    topics: [
      {
        id: 'thai-grammar',
        subjectId: 'thai',
        name: 'หลักภาษาและการใช้ภาษา',
        slug: 'grammar',
        description: 'ชนิดของคำ คำสมาส สนธิ ประโยค คำราชาศัพท์ และคำยืมภาษาต่างประเทศ',
        icon: 'PenTool',
        totalQuestions: 50,
        order: 1,
      },
      {
        id: 'thai-reading',
        subjectId: 'thai',
        name: 'การอ่านวิเคราะห์และการตีความ',
        slug: 'reading',
        description: 'การจับใจความสำคัญ เจตนาผู้เขียน ข้อเท็จจริง-ข้อคิดเห็น และสำนวนไทย',
        icon: 'FileText',
        totalQuestions: 50,
        order: 2,
      },
    ],
  },
  {
    id: 'social',
    name: 'สังคมศึกษา',
    nameEn: 'Social Studies',
    slug: 'social',
    icon: 'Compass',
    color: '#EF4444', // Red
    bgColor: '#FEF2F2',
    borderColor: '#FECACA',
    description: 'ภูมิศาสตร์ แผนที่ เศรษฐศาสตร์ หน้าที่พลเมือง ประวัติศาสตร์ และข่าวสารปัจจุบัน',
    totalQuestions: 100,
    order: 5,
    topics: [
      {
        id: 'soc-geography-econ',
        subjectId: 'social',
        name: 'ภูมิศาสตร์และเศรษฐศาสตร์',
        slug: 'geography-econ',
        description: 'เครื่องมือทางภูมิศาสตร์ พิกัด แผนที่ กลไกราคา อุปสงค์-อุปทาน สถาบันการเงิน',
        icon: 'MapPin',
        totalQuestions: 50,
        order: 1,
      },
      {
        id: 'soc-civics-history',
        subjectId: 'social',
        name: 'หน้าที่พลเมือง ศาสนา และประวัติศาสตร์',
        slug: 'civics-history',
        description: 'รัฐธรรมนูญ กฎหมายเบื้องต้น พุทธประวัติและหลักธรรม ประวัติศาสตร์ไทยและอุบลฯ/อีสาน',
        icon: 'Landmark',
        totalQuestions: 50,
        order: 2,
      },
    ],
  },
];
